branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: dojo-eb
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: dojo
  repository: null
  sc: git
  workspace_type: Application
